<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UpstreamCause>
            <upstreamProject>1-build-pipeline/1-build-pipeline</upstreamProject>
            <upstreamUrl>job/1-build-pipeline/job/1-build-pipeline/</upstreamUrl>
            <upstreamBuild>28</upstreamBuild>
            <upstreamCauses>
              <hudson.model.Cause_-UserIdCause>
                <userId>lemaxadmin</userId>
              </hudson.model.Cause_-UserIdCause>
            </upstreamCauses>
          </hudson.model.Cause_-UpstreamCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <org.jenkinsci.plugins.workflow.support.steps.build.BuildUpstreamNodeAction plugin="pipeline-build-step@2.10">
      <upstreamNodeId>7</upstreamNodeId>
      <upstreamRunId>1-build-pipeline/1-build-pipeline#28</upstreamRunId>
    </org.jenkinsci.plugins.workflow.support.steps.build.BuildUpstreamNodeAction>
    <jenkins.model.InterruptedBuildAction>
      <causes class="com.google.common.collect.ImmutableList">
        <org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerCancelledCause plugin="pipeline-build-step@2.10">
          <cause class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.21">
            <stackTrace>
              <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1137)</trace>
              <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:367)</trace>
              <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)</trace>
              <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
              <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
              <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)</trace>
              <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
              <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
              <trace>java.lang.Thread.run(Thread.java:748)</trace>
            </stackTrace>
            <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </suppressedExceptions>
            <result>ABORTED</result>
            <causes class="java.util.Arrays$ArrayList">
              <a class="jenkins.model.CauseOfInterruption-array">
                <jenkins.model.CauseOfInterruption_-UserInterruption>
                  <user>lemaxadmin</user>
                </jenkins.model.CauseOfInterruption_-UserInterruption>
              </a>
            </causes>
          </cause>
        </org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerCancelledCause>
      </causes>
    </jenkins.model.InterruptedBuildAction>
  </actions>
  <queueId>202</queueId>
  <timestamp>1577567724094</timestamp>
  <startTime>1577567724102</startTime>
  <result>ABORTED</result>
  <duration>267</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/lib/jenkins/workspace/1-build-pipeline/1.1-build-pipeline-jobs/level-1-build-server</workspace>
  <hudsonVersion>2.204.1</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="com.google.common.collect.EmptyImmutableSortedSet"/>
</build>